### ISSUE TITLE
Use

### ISSUE THREAD

**Issue by iPredictable** [aKalisch/source-bunnyhop#7]
@Acornay bro if u teach me how to use this source ill give u 30$ on paypal.

**Comment by MyNameIsLebronJames** [comment]
@PredictEr what's your Skype? i'll tell you what to do :)

**Comment by bertrand2012** [comment]
@Acornay please help me .

**Comment by MyNameIsLebronJames** [comment]
@acer2245 add me on  Skype? mine is strik3rdoom

**Comment by iPredictable** [comment]
@Acornay added u bro

**Comment by extrenebiibues** [comment]
@Acornay i added u too please help me @PredictEr if u know find out how to tell me please my skype is briancela        nickname is (cocaine)

**Comment by iPredictable** [comment]
@extrenebiibues I didn't find out how but I found a mac multihack which is better. Walls, bhop, triggerbot, aimbot, aim assist. Add my skype if u want help. kasra.gamer
