### ISSUE TITLE
Problem with GetKeys

### ISSUE THREAD

**Issue by sacredgeo** [aKalisch/source-bunnyhop#8]
@aKalisch 

I'm trying to add this into the glow cheat. I run into a problem trying to build it. I get errors with GetKeys.

```
 Undefined symbols for architecture x86_64:
   "_GetKeys", referenced from:
       isPressed(unsigned short) in main.o
 ld: symbol(s) not found for architecture x86_64
 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm able to use sendKey. I can detect m_fFlags. The only problem is detecting the spacebar. What do you think of that error? Thank you.

**Comment by aKalisch** [comment]
@sacredgeo 
This is no problem ;-)
On top of the file is the Carbon/Carbon.h file included. You need to include it in your Hackbase also.

And you need to link it to your Binary in xCode: Build Phases -> Link Binary With Libraries

**Comment by sacredgeo** [comment]
@aKalisch 

Build succeeded! Thank you sir!

It's really funny you mention that because I was just looking at this code on google and I saw at the bottom it's talking about the carbon framework. 

http://stackoverflow.com/questions/16150267/mac-os-x-get-state-of-spacebar/16283140#16283140

**Comment by sacredgeo** [comment]
It's working perfectly. I still haven't created the array for velocity, but I'll work on it soon.

**Comment by veb** [comment]
For anyone else, technically Carbon has been depreciated but you still need to add the Carbon framework to your project. Like:
![image](https://cloud.githubusercontent.com/assets/376245/19832417/c2ef77b6-9e7f-11e6-9a23-b2ab1b8d49be.png)

**Comment by LittleCheater** [comment]
sacredgeo, can you give me the code? I can't get it to work.
